// Code generated by goctl. DO NOT EDIT.
// Source: example.proto

package example

import (
	"context"

	"go-zero-example/micro/example/proto/example"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExampleRequest  = example.ExampleRequest
	ExampleResponse = example.ExampleResponse

	Example interface {
		Hello(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
	}

	defaultExample struct {
		cli zrpc.Client
	}
)

func NewExample(cli zrpc.Client) Example {
	return &defaultExample{
		cli: cli,
	}
}

func (m *defaultExample) Hello(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	client := example.NewExampleClient(m.cli.Conn())
	return client.Hello(ctx, in, opts...)
}
