// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	example "go-zero-example/server/internal/handler/example"
	hello "go-zero-example/server/internal/handler/hello"
	ping "go-zero-example/server/internal/handler/ping"
	"go-zero-example/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: example.GetExampleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/example"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: hello.GetHelloHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/hello"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ping.GetPingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/ping"),
	)
}
