// Code generated by goctl. DO NOT EDIT.
package types

type ExampleRequest struct {
}

type ExampleResponse struct {
	Msg string `json:"msg"`
}

type HelloRequest struct {
}

type HelloResponse struct {
	Msg string `json:"msg"`
}

type PingRequest struct {
}

type PingResponse struct {
	Msg string `json:"msg"`
}
